#### Split Task

 first task is to split each row of data.csv into text file , 
the file name is the id column and the text is the content of text column

here is the datset , want the name of outp of each text is the id number 
and the content is the text inside each text for the same id

In [0]:
# Load EDA Pkgs
import pandas as pd 
import numpy as np

In [0]:
# Load Dataset
df = pd.read_csv("last.csv")

In [0]:
df.head()

,Unnamed: 0,Unnamed: 0.1,id,text,EF_Label,Sentence_with_EF
0,2,2,13702,Admission Date: [**2119-5-4**] D...,0.0,"['EF 63%), ^chol, hypothyroidism, htn,', 'EF 6..."
1,11,11,1136,Admission Date: [**2192-4-19**] ...,1.0,['EF 40%)']
2,17,17,79900,Admission Date: [**2194-7-18**] ...,1.0,"['EF 35%)', 'EF 35%), AICD p/w SOB and']"
3,21,21,9805,Admission Date: [**2131-7-5**] D...,1.0,"['EF 28%.', 'EF 28%, akinetic apex, LV mural']"
4,36,36,30812,Admission Date: [**2143-11-22**] ...,0.0,['EF 70%) The right ventricular free wall is']

In [0]:
# Shape
df.shape

(7115, 6)

In [0]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'id', 'text', 'EF_Label',
       'Sentence_with_EF'],
      dtype='object')

In [0]:
df = df[['id', 'text']]

In [0]:
df.head()

      id                                               text
0  13702  Admission Date:  [**2119-5-4**]              D...
1   1136  Admission Date:  [**2192-4-19**]              ...
2  79900  Admission Date:  [**2194-7-18**]              ...
3   9805  Admission Date:  [**2131-7-5**]              D...
4  30812  Admission Date:  [**2143-11-22**]             ...

#### Method  1
+ Step 1 Group all By ID
+ Step 2  Join All Text of the Same ID As One

In [0]:

grouped_df =  df.groupby('id').agg({
    'text': lambda x: ', '.join(x),
})

In [0]:
# Shape
grouped_df.shape

(7115, 1)

In [0]:
# Len of Unique Rows
len(df['id'].unique().tolist())

7115

In [0]:
# Len of Unique Rows For Index
len(grouped_df.index.tolist())

7115

#### Narrative
+ Both have the same len

In [0]:
# Already Sorted
grouped_df.index

Int64Index([    4,    21,    32,    37,    42,    55,    68,    85,    88,
              105,
            ...
            99870, 99883, 99893, 99901, 99913, 99938, 99957, 99982, 99985,
            99995],
           dtype='int64', name='id', length=7115)

In [0]:
id_list = grouped_df.index.tolist()

In [0]:
id_list

[4,
 21,
 32,
 37,
 42,
 55,
 68,
 85,
 88,
 105,
 106,
 107,
 109,
 111,
 133,
 138,
 140,
 164,
 175,
 176,
 188,
 191,
 192,
 199,
 205,
 209,
 210,
 211,
 213,
 218,
 222,
 223,
 231,
 234,
 235,
 236,
 246,
 249,
 256,
 270,
 272,
 291,
 298,
 305,
 313,
 323,
 328,
 353,
 357,
 368,
 369,
 378,
 382,
 383,
 389,
 391,
 393,
 394,
 414,
 415,
 422,
 423,
 425,
 426,
 445,
 454,
 464,
 492,
 494,
 507,
 518,
 530,
 533,
 538,
 540,
 543,
 544,
 546,
 568,
 580,
 584,
 586,
 588,
 618,
 629,
 631,
 641,
 652,
 653,
 665,
 679,
 682,
 689,
 690,
 698,
 703,
 710,
 711,
 720,
 722,
 725,
 731,
 733,
 734,
 735,
 740,
 743,
 773,
 787,
 794,
 798,
 801,
 805,
 811,
 816,
 820,
 831,
 835,
 846,
 852,
 874,
 882,
 890,
 894,
 902,
 914,
 923,
 946,
 947,
 952,
 960,
 975,
 998,
 1003,
 1006,
 1017,
 1020,
 1021,
 1036,
 1039,
 1040,
 1041,
 1050,
 1069,
 1079,
 1088,
 1102,
 1104,
 1108,
 1112,
 1113,
 1114,
 1120,
 1124,
 1135,
 1136,
 1157,
 1187,
 1194,
 1197,
 1207,
 1222,
 1228,
 1234,
 1239,
 1244,
 1247,
 1263,
 1266,
 1268,
 1280,
 1281,
 1283,
 1313,
 1317,
 1320,
 1329,
 1337,
 1339,
 1348,
 1351,
 1354,
 1371,
 1386,
 1396,
 1417,
 1423,
 1426,
 1430,
 1439,
 1441,
 1472,
 1474,
 1487,
 1501,
 1516,
 1517,
 1527,
 1541,
 1544,
 1557,
 1574,
 1578,
 1601,
 1608,
 1610,
 1616,
 1649,
 1677,
 1679,
 1684,
 1693,
 1699,
 1700,
 1701,
 1709,
 1715,
 1725,
 1726,
 1763,
 1767,
 1770,
 1804,
 1811,
 1816,
 1819,
 1822,
 1825,
 1840,
 1855,
 1860,
 1885,
 1886,
 1900,
 1901,
 1902,
 1914,
 1931,
 1944,
 1972,
 1985,
 1986,
 1999,
 2002,
 2005,
 2016,
 2021,
 2025,
 2032,
 2042,
 2049,
 2061,
 2063,
 2066,
 2078,
 2087,
 2090,
 2091,
 2105,
 2113,
 2129,
 2136,
 2153,
 2155,
 2157,
 2207,
 2208,
 2213,
 2240,
 2258,
 2262,
 2265,
 2280,
 2324,
 2332,
 2338,
 2343,
 2361,
 2362,
 2363,
 2364,
 2369,
 2378,
 2392,
 2404,
 2415,
 2423,
 2425,
 2427,
 2446,
 2460,
 2479,
 2497,
 2498,
 2503,
 2506,
 2511,
 2512,
 2513,
 2516,
 2539,
 2550,
 2554,
 2558,
 2562,
 2581,
 2586,
 2589,
 2590,
 2592,
 2598,
 2613,
 2619,
 2625,
 2628,
 2635,
 2636,
 2639,
 2640,
 2644,
 2649,
 2652,
 2657,
 2664,
 2670,
 2679,
 2688,
 2693,
 2703,
 2708,
 2712,
 2718,
 2719,
 2755,
 2757,
 2758,
 2769,
 2788,
 2790,
 2821,
 2825,
 2850,
 2854,
 2881,
 2885,
 2894,
 2902,
 2905,
 2906,
 2912,
 2921,
 2941,
 2961,
 2962,
 2984,
 2985,
 2990,
 3007,
 3010,
 3011,
 3019,
 3022,
 3042,
 3055,
 3057,
 3068,
 3089,
 3102,
 3105,
 3118,
 3123,
 3145,
 3178,
 3179,
 3214,
 3216,
 3217,
 3218,
 3220,
 3221,
 3226,
 3234,
 3243,
 3250,
 3251,
 3265,
 3267,
 3272,
 3274,
 3283,
 3287,
 3288,
 3294,
 3297,
 3323,
 3326,
 3347,
 3356,
 3377,
 3389,
 3392,
 3397,
 3417,
 3426,
 3433,
 3436,
 3460,
 3463,
 3466,
 3471,
 3474,
 3482,
 3491,
 3494,
 3496,
 3506,
 3530,
 3540,
 3543,
 3554,
 3556,
 3566,
 3575,
 3591,
 3600,
 3601,
 3607,
 3640,
 3644,
 3650,
 3678,
 3683,
 3704,
 3705,
 3722,
 3727,
 3728,
 3746,
 3748,
 3792,
 3798,
 3815,
 3830,
 3838,
 3840,
 3841,
 3842,
 3846,
 3852,
 3861,
 3866,
 3874,
 3879,
 3891,
 3897,
 3903,
 3910,
 3913,
 3917,
 3929,
 3935,
 3940,
 3952,
 3969,
 3974,
 3977,
 3978,
 3980,
 3987,
 3995,
 4013,
 4054,
 4059,
 4063,
 4070,
 4072,
 4074,
 4079,
 4098,
 4113,
 4115,
 4120,
 4130,
 4138,
 4155,
 4216,
 4239,
 4240,
 4251,
 4254,
 4257,
 4260,
 4268,
 4269,
 4275,
 4292,
 4313,
 4326,
 4329,
 4334,
 4354,
 4359,
 4390,
 4401,
 4410,
 4428,
 4453,
 4464,
 4469,
 4485,
 4490,
 4496,
 4497,
 4518,
 4550,
 4564,
 4577,
 4587,
 4591,
 4599,
 4600,
 4606,
 4614,
 4619,
 4635,
 4644,
 4646,
 4655,
 4675,
 4685,
 4688,
 4690,
 4696,
 4700,
 4708,
 4710,
 4713,
 4735,
 4741,
 4754,
 4762,
 4766,
 4770,
 4776,
 4787,
 4802,
 4807,
 4808,
 4809,
 4813,
 4816,
 4829,
 4833,
 4843,
 4848,
 4868,
 4874,
 4875,
 4882,
 4883,
 4891,
 4893,
 4902,
 4906,
 4908,
 4915,
 4923,
 4929,
 4939,
 4947,
 4951,
 4955,
 4966,
 4968,
 4969,
 4976,
 5004,
 5005,
 5029,
 5030,
 5033,
 5047,
 5058,
 5062,
 5069,
 5071,
 5076,
 5077,
 5078,
 5090,
 5096,
 5097,
 5099,
 5112,
 5126,
 5128,
 5145,
 5158,
 5161,
 5180,
 5188,
 5190,
 5196,
 5199,
 5206,
 5226,
 5228,
 5229,
 5236,
 5244,
 5245,
 5284,
 5285,
 5289,
 5304,
 5308,
 5321,
 5324,
 5330,
 5331,
 5348,
 5353,
 5362,
 5365,
 5367,
 5369,
 5370,
 5383,
 5397,
 5400,
 5410,
 5434,
 5446,
 5453,
 5469,
 5470,
 5472,
 5474,
 5476,
 5481,
 5485,
 5487,
 5488,
 5493,
 5494,
 5504,
 5506,
 5525,
 5527,
 5528,
 5534,
 5535,
 5536,
 5537,
 5544,
 5551,
 5555,
 5560,
 5573,
 5575,
 5579,
 5586,
 5596,
 5603,
 5606,
 5614,
 5619,
 5623,
 5634,
 5643,
 5647,
 5658,
 5672,
 5676,
 5679,
 5689,
 5692,
 5705,
 5727,
 5760,
 5771,
 5772,
 5774,
 5783,
 5788,
 5794,
 5795,
 5812,
 5823,
 5832,
 5865,
 5867,
 5869,
 5874,
 5882,
 5890,
 5901,
 5905,
 5909,
 5922,
 5935,
 5950,
 5954,
 5982,
 6000,
 6012,
 6016,
 6024,
 6027,
 6048,
 6053,
 6063,
 6069,
 6078,
 6079,
 6083,
 6086,
 6099,
 6116,
 6124,
 6133,
 6134,
 6135,
 6156,
 6158,
 6160,
 6166,
 6178,
 6189,
 6194,
 6195,
 6196,
 6202,
 6206,
 6211,
 6222,
 6244,
 6246,
 6255,
 6258,
 6262,
 6270,
 6272,
 6279,
 6290,
 6292,
 6294,
 6304,
 6315,
 6317,
 6334,
 6335,
 6349,
 6352,
 6353,
 6364,
 6375,
 6378,
 6381,
 6398,
 6411,
 6414,
 6421,
 6423,
 6440,
 6448,
 6461,
 6466,
 6474,
 6481,
 6498,
 6503,
 6510,
 6513,
 6519,
 6533,
 6534,
 6535,
 6539,
 6540,
 6542,
 6543,
 6564,
 6575,
 6576,
 6578,
 6589,
 6597,
 6598,
 6602,
 6613,
 6621,
 6624,
 6628,
 6639,
 6647,
 6651,
 6661,
 6670,
 6682,
 6692,
 6695,
 6697,
 6707,
 6709,
 6722,
 6723,
 6735,
 6739,
 6745,
 6756,
 6758,
 6759,
 6767,
 6787,
 6789,
 6791,
 6805,
 6809,
 6830,
 6873,
 6878,
 6884,
 6891,
 6898,
 6901,
 6910,
 6912,
 6916,
 6917,
 6928,
 6942,
 6950,
 6973,
 6976,
 6979,
 6990,
 6996,
 6999,
 7001,
 7010,
 7013,
 7014,
 7018,
 7029,
 7042,
 7051,
 7053,
 7095,
 7101,
 7103,
 7105,
 7107,
 7110,
 7118,
 7138,
 7158,
 7161,
 7177,
 7178,
 7180,
 7188,
 7192,
 7210,
 7212,
 7214,
 7223,
 7224,
 7247,
 7250,
 7251,
 7253,
 7258,
 7262,
 7275,
 7283,
 7297,
 7299,
 7306,
 7319,
 7323,
 7357,
 7363,
 7364,
 7367,
 7386,
 7391,
 7401,
 7407,
 7429,
 7445,
 7449,
 7460,
 7464,
 7473,
 7482,
 7486,
 7487,
 7495,
 7511,
 7515,
 7533,
 7539,
 7542,
 7549,
 7557,
 7577,
 7583,
 7589,
 7604,
 7614,
 7616,
 7618,
 7621,
 7650,
 7656,
 7659,
 7666,
 7671,
 7675,
 7676,
 7686,
 7693,
 7695,
 7696,
 7706,
 7709,
 7710,
 7715,
 7726,
 7756,
 7778,
 7782,
 7798,
 7799,
 7804,
 7809,
 7815,
 7818,
 7826,
 7839,
 7840,
 7842,
 7853,
 7874,
 7897,
 7900,
 7904,
 7918,
 7930,
 7936,
 7939,
 7952,
 7959,
 7965,
 7973,
 7988,
 7993,
 7998,
 8006,
 8013,
 8014,
 8037,
 8050,
 8081,
 8105,
 8109,
 8115,
 8120,
 8130,
 8132,
 8145,
 8152,
 8167,
 8170,
 8177,
 8182,
 8188,
 8201,
 8222,
 8227,
 8231,
 8233,
 8258,
 8293,
 8314,
 8323,
 8324,
 8331,
 8332,
 8337,
 8373,
 8374,
 8380,
 8389,
 8396,
 8402,
 8426,
 8427,
 8431,
 ...]

In [0]:
for i,row in zip(id_list,grouped_df.values):
    file_name = '{}.txt'.format(i)
    row.tofile(file_name, sep=",", format="%s")
    i+=1